// <auto-generated />
namespace MyMeetings.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedtomodelsfunctionalwithsubscribing : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedtomodelsfunctionalwithsubscribing));
        
        string IMigrationMetadata.Id
        {
            get { return "201701161130506_Added-to-models-functional-with-subscribing"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
